const ru = {
  'catalog.eyebrow': 'Коллекция Roamly', 'catalog.title': 'Каталог', 'catalog.titleAccent': 'направлений',
  'catalog.intro': 'Места, ради которых стоит собрать чемодан. Сравните настроение, бюджет и детали въезда — всё остальное оставьте путешествию.',
  'catalog.resultOne': 'направление', 'catalog.resultFew': 'направления', 'catalog.resultMany': 'направлений',
  'catalog.sort': 'Сортировка', 'catalog.sortFeatured': 'Сначала рекомендуемые', 'catalog.sortCheap': 'Сначала дешевле', 'catalog.sortExpensive': 'Сначала дороже', 'catalog.sortRating': 'По рейтингу', 'catalog.sortAlphabetical': 'По алфавиту',
  'catalog.emptyCount': '0 направлений', 'catalog.emptyTitle': 'Расширим горизонт?', 'catalog.emptyText': 'По этому сочетанию фильтров ничего не найдено. Сбросьте часть условий или начните сначала.', 'catalog.reset': 'Сбросить фильтры',
  'filters.label': 'Фильтры направлений', 'filters.title': 'Подберите своё направление', 'filters.resetAll': 'Сбросить всё', 'filters.region': 'Регион', 'filters.allRegions': 'Все регионы', 'filters.rating': 'Рейтинг от', 'filters.any': 'Любой', 'filters.visa': 'Визовый режим', 'filters.budget': 'Бюджет на поездку', 'filters.from': 'от {price}', 'filters.to': 'до {price}', 'filters.minPrice': 'Минимальная цена', 'filters.maxPrice': 'Максимальная цена', 'filters.interests': 'Что вам интересно', 'filters.anyTag': 'любой из выбранных тегов',
  'filters.regionEurasia': 'Евразия', 'filters.regionCaucasus': 'Кавказ', 'filters.regionEurope': 'Европа', 'filters.regionEastAsia': 'Восточная Азия', 'filters.regionSoutheastAsia': 'Юго-Восточная Азия', 'filters.regionSouthAsia': 'Южная Азия', 'filters.regionNorthAmerica': 'Северная Америка', 'filters.beach': 'Пляж', 'filters.culture': 'Культура', 'filters.adventure': 'Приключения', 'filters.city': 'Город', 'filters.nature': 'Природа', 'filters.food': 'Гастрономия', 'filters.traditional': 'Традиции', 'filters.visaFree': 'Без визы', 'filters.visaArrival': 'По прибытии', 'filters.visaAdvance': 'Заранее',
  'vote.loadError': 'Не удалось загрузить ваш голос.', 'vote.saveError': 'Не удалось сохранить голос. Проверьте интернет и попробуйте снова.', 'vote.eyebrow': 'Выбор сообщества', 'vote.shareDream': 'Поделитесь направлением мечты', 'vote.leaderFallback': 'Сейчас это самое желанное направление среди наших путешественников.', 'vote.prompt': 'Выберите настоящий город из подсказок. Один аккаунт — один актуальный голос.', 'vote.total': 'всего голосов', 'vote.top': 'Топ-4 направления', 'vote.statsUnavailable': 'Статистика временно недоступна', 'vote.checking': 'Проверяем аккаунт…', 'vote.signInPrompt': 'Войдите в аккаунт, чтобы проголосовать.', 'vote.login': 'Войти', 'vote.signup': 'Регистрация', 'vote.current': 'Ваш текущий выбор:', 'vote.question': 'Куда бы вы хотели поехать?', 'vote.saved': 'Голос сохранён!', 'vote.saving': 'Сохраняем…', 'vote.change': 'Изменить голос', 'vote.submit': 'Проголосовать',
  'map.eyebrow': 'Исследуйте мир', 'map.title': 'Все направления.', 'map.titleAccent': 'На одной карте.', 'map.countText': 'мест от Европы до Азии. Нажмите на метку, чтобы познакомиться ближе.', 'map.hint': 'Перемещайте карту и приближайте', 'map.close': 'Закрыть превью', 'map.tripEstimate': 'Ориентир на поездку', 'map.openGuide': 'Открыть путеводитель', 'map.aria': 'Интерактивная карта направлений',
  'guide.notFound': 'Направление не найдено', 'guide.backCatalog': 'К каталогу', 'guide.nextStep': 'Следующий шаг', 'guide.planTitle': 'Соберите поездку под себя', 'guide.createRoute': 'Создать маршрут', 'guide.panorama': 'Панорама направления {city}', 'guide.all': 'Все направления', 'guide.label': 'Путеводитель', 'guide.updated': 'Обновлено 12 августа 2026', 'guide.scroll': 'Перейти к путеводителю', 'guide.inThisGuide': 'В этом гиде', 'guide.whatToSee': 'Что посмотреть', 'guide.seasonBudget': 'Сезон и бюджет', 'guide.goodToKnow': 'Важно знать', 'guide.whyGo': 'Почему стоит ехать', 'guide.highlights': 'Главное', 'guide.highlightsText': 'Не список для галочки, а места, через которые лучше всего чувствуется характер направления.', 'guide.beforeTrip': 'Перед поездкой', 'guide.practical': 'Практическая сторона', 'guide.when': 'Когда ехать', 'guide.climate': 'Климат и сезонность', 'guide.entry': 'Виза и въезд · паспорт Казахстана', 'guide.estimate': 'Ориентир', 'guide.howMuch': 'Сколько заложить', 'guide.budgetNote': 'Средний комфортный бюджет без перелёта. Цены меняются по сезону и курсу валют.', 'guide.knowAhead': 'Знать заранее', 'guide.calmTitle': 'Путешествовать спокойно', 'guide.calmText': 'Не повод тревожиться — просто несколько деталей, которые помогут избежать неприятных сюрпризов.', 'guide.culture': 'Культурный код', 'guide.prepareFor': 'К чему быть готовым',
} as const;

const en: { [K in keyof typeof ru]: string } = {
  'catalog.eyebrow': 'The Roamly collection', 'catalog.title': 'Destination', 'catalog.titleAccent': 'collection', 'catalog.intro': 'Places worth packing for. Compare the atmosphere, budget, and entry essentials — then leave room for the journey itself.', 'catalog.resultOne': 'destination', 'catalog.resultFew': 'destinations', 'catalog.resultMany': 'destinations', 'catalog.sort': 'Sort by', 'catalog.sortFeatured': 'Recommended first', 'catalog.sortCheap': 'Lowest price first', 'catalog.sortExpensive': 'Highest price first', 'catalog.sortRating': 'Highest rated', 'catalog.sortAlphabetical': 'Alphabetical', 'catalog.emptyCount': '0 destinations', 'catalog.emptyTitle': 'Broaden the horizon?', 'catalog.emptyText': 'Nothing matches this combination of filters. Remove a few conditions or begin again.', 'catalog.reset': 'Reset filters',
  'filters.label': 'Destination filters', 'filters.title': 'Find your kind of destination', 'filters.resetAll': 'Reset all', 'filters.region': 'Region', 'filters.allRegions': 'All regions', 'filters.rating': 'Minimum rating', 'filters.any': 'Any', 'filters.visa': 'Entry requirements', 'filters.budget': 'Trip budget', 'filters.from': 'from {price}', 'filters.to': 'up to {price}', 'filters.minPrice': 'Minimum price', 'filters.maxPrice': 'Maximum price', 'filters.interests': 'What inspires you', 'filters.anyTag': 'match any selected tag',
  'filters.regionEurasia': 'Eurasia', 'filters.regionCaucasus': 'Caucasus', 'filters.regionEurope': 'Europe', 'filters.regionEastAsia': 'East Asia', 'filters.regionSoutheastAsia': 'Southeast Asia', 'filters.regionSouthAsia': 'South Asia', 'filters.regionNorthAmerica': 'North America', 'filters.beach': 'Beach', 'filters.culture': 'Culture', 'filters.adventure': 'Adventure', 'filters.city': 'City life', 'filters.nature': 'Nature', 'filters.food': 'Food', 'filters.traditional': 'Tradition', 'filters.visaFree': 'Visa-free', 'filters.visaArrival': 'On arrival', 'filters.visaAdvance': 'In advance',
  'vote.loadError': 'We couldn’t load your vote.', 'vote.saveError': 'We couldn’t save your vote. Check your connection and try again.', 'vote.eyebrow': 'The community’s choice', 'vote.shareDream': 'Share your dream destination', 'vote.leaderFallback': 'This is currently the most wanted destination among Roamly travellers.', 'vote.prompt': 'Choose a real city from the suggestions. One account keeps one current vote.', 'vote.total': 'votes in total', 'vote.top': 'Top 4 destinations', 'vote.statsUnavailable': 'Statistics are temporarily unavailable', 'vote.checking': 'Checking your account…', 'vote.signInPrompt': 'Sign in to cast your vote.', 'vote.login': 'Sign in', 'vote.signup': 'Create account', 'vote.current': 'Your current choice:', 'vote.question': 'Where would you love to go?', 'vote.saved': 'Vote saved!', 'vote.saving': 'Saving…', 'vote.change': 'Change vote', 'vote.submit': 'Vote',
  'map.eyebrow': 'Explore the world', 'map.title': 'Every destination.', 'map.titleAccent': 'On one map.', 'map.countText': 'places from Europe to Asia. Select a marker to take a closer look.', 'map.hint': 'Move and zoom the map', 'map.close': 'Close preview', 'map.tripEstimate': 'Indicative trip budget', 'map.openGuide': 'Open travel guide', 'map.aria': 'Interactive destination map',
  'guide.notFound': 'Destination not found', 'guide.backCatalog': 'Back to the collection', 'guide.nextStep': 'Next step', 'guide.planTitle': 'Shape the trip around you', 'guide.createRoute': 'Create itinerary', 'guide.panorama': 'Panorama of {city}', 'guide.all': 'All destinations', 'guide.label': 'Travel guide', 'guide.updated': 'Updated 12 August 2026', 'guide.scroll': 'Jump to the guide', 'guide.inThisGuide': 'In this guide', 'guide.whatToSee': 'What to see', 'guide.seasonBudget': 'Season and budget', 'guide.goodToKnow': 'Good to know', 'guide.whyGo': 'Why it is worth the journey', 'guide.highlights': 'The essentials', 'guide.highlightsText': 'Not a checklist, but the places that best reveal the destination’s character.', 'guide.beforeTrip': 'Before you go', 'guide.practical': 'Practical essentials', 'guide.when': 'When to go', 'guide.climate': 'Climate and seasons', 'guide.entry': 'Visa and entry · Kazakhstan passport', 'guide.estimate': 'A useful estimate', 'guide.howMuch': 'What to budget', 'guide.budgetNote': 'A comfortable mid-range budget excluding flights. Prices vary with season and exchange rates.', 'guide.knowAhead': 'Know before you go', 'guide.calmTitle': 'Travel with confidence', 'guide.calmText': 'Nothing alarming — simply a few details that help you avoid unwelcome surprises.', 'guide.culture': 'Local culture', 'guide.prepareFor': 'What to expect',
};

export const catalogTranslations = { ru, en };
