const ru = {
  'city.placeholder': 'Начните вводить город', 'city.searchError': 'Не удалось найти города. Попробуйте ещё раз.', 'city.choose': 'Выберите город из списка подсказок.', 'city.searching': 'Ищем города', 'city.empty': 'Города не найдены',
  'guest.browserError': 'Не удалось временно сохранить маршрут. Освободите место в браузере и попробуйте снова.', 'guest.close': 'Закрыть', 'guest.eyebrow': 'Ваш первый маршрут готов', 'guest.title': 'Сохраните эту поездку и продолжайте планировать новые', 'guest.text': 'Зарегистрируйтесь бесплатно, чтобы создавать новые маршруты и возвращаться к своим планам в любое время.', 'guest.signup': 'Зарегистрироваться бесплатно', 'guest.login': 'Уже есть аккаунт',
  'setup.title': 'Сначала подключите Supabase', 'setup.text': 'Скопируйте .env.example в .env и добавьте URL и Publishable key своего проекта.',
  'quick.destination': 'Куда хотите?', 'quick.daysNights': 'Дней / ночей', 'quick.days': 'Количество дней', 'quick.nights': 'Количество ночей', 'quick.travelers': 'Путешественники', 'quick.people': '{count} чел.', 'quick.style': 'Стиль поездки', 'quick.comfort': 'Комфорт', 'quick.economy': 'Экономно', 'quick.premium': 'Премиум', 'quick.submit': 'Создать план →',
  'extras.road': 'Дорога и город', 'extras.transport': 'Транспорт', 'extras.stayEyebrow': 'Где остановиться', 'extras.stays': 'Варианты жилья', 'extras.foodEyebrow': 'Вкус направления', 'extras.food': 'Рестораны и еда', 'extras.overview': 'Общий обзор', 'extras.activities': 'Активности', 'extras.before': 'Перед поездкой', 'extras.links': 'Полезные ссылки', 'extras.remember': 'Ничего не забыть', 'extras.checklist': 'Подготовка / чек-лист', 'extras.perNight': '/ ночь',
  'routeMap.dayMeta': 'День {day} · {time}', 'routeMap.area': 'положение по району', 'routeMap.alt': '{title}, день {day}', 'routeMap.aria': 'Интерактивная карта точек маршрута',
  'password.levelWeak': 'Слабый', 'password.levelMedium': 'Средний', 'password.levelStrong': 'Надёжный', 'password.hintLength': 'минимум 10 символов', 'password.hintGroups': 'буквы разного регистра, цифры или символы', 'password.hintPatterns': 'без простых последовательностей и повторов',
};
const en: { [K in keyof typeof ru]: string } = {
  'city.placeholder': 'Start typing a city', 'city.searchError': 'We couldn’t find cities. Please try again.', 'city.choose': 'Choose a city from the suggestions.', 'city.searching': 'Searching for cities', 'city.empty': 'No cities found',
  'guest.browserError': 'We couldn’t temporarily save this itinerary. Free some browser storage and try again.', 'guest.close': 'Close', 'guest.eyebrow': 'Your first itinerary is ready', 'guest.title': 'Save this trip and keep planning what comes next', 'guest.text': 'Create a free account to build more itineraries and return to your plans whenever you wish.', 'guest.signup': 'Create a free account', 'guest.login': 'I already have an account',
  'setup.title': 'Connect Supabase first', 'setup.text': 'Copy .env.example to .env and add your project URL and Publishable key.',
  'quick.destination': 'Where to?', 'quick.daysNights': 'Days / nights', 'quick.days': 'Number of days', 'quick.nights': 'Number of nights', 'quick.travelers': 'Travellers', 'quick.people': '{count} people', 'quick.style': 'Travel style', 'quick.comfort': 'Comfort', 'quick.economy': 'Value', 'quick.premium': 'Premium', 'quick.submit': 'Create plan →',
  'extras.road': 'Getting there and around', 'extras.transport': 'Transport', 'extras.stayEyebrow': 'Where to stay', 'extras.stays': 'Selected stays', 'extras.foodEyebrow': 'A taste of the destination', 'extras.food': 'Restaurants and food', 'extras.overview': 'At a glance', 'extras.activities': 'Activities', 'extras.before': 'Before you leave', 'extras.links': 'Useful guidance', 'extras.remember': 'Nothing left behind', 'extras.checklist': 'Preparation checklist', 'extras.perNight': '/ night',
  'routeMap.dayMeta': 'Day {day} · {time}', 'routeMap.area': 'approximate area', 'routeMap.alt': '{title}, day {day}', 'routeMap.aria': 'Interactive itinerary map',
  'password.levelWeak': 'Weak', 'password.levelMedium': 'Good', 'password.levelStrong': 'Strong', 'password.hintLength': 'at least 10 characters', 'password.hintGroups': 'upper- and lowercase letters, numbers, or symbols', 'password.hintPatterns': 'avoid simple sequences and repeated characters',
};
export const commonTranslations = { ru, en };
