const ru = {
  'planner.example1': 'Хочу неделю в Японии: природа, небольшие кафе и спокойный темп…', 'planner.example2': 'Море в феврале для двоих, красивый отель и минимум туристических мест…', 'planner.example3': 'Соберите семейное путешествие по Италии с детьми и без спешки…', 'planner.example4': 'Мечтаю увидеть северное сияние и пожить пару ночей в уютном домике…',
  'planner.errorAges': 'Укажите возраст целыми числами от 0 до 120 через запятую.', 'planner.errorDatesBoth': 'Укажите обе даты поездки или оставьте обе пустыми.', 'planner.errorDatesOrder': 'Дата окончания раньше даты начала. Исправьте даты.', 'planner.errorAgeCount': 'Возрастов не может быть больше, чем путешественников.', 'planner.errorBudgetBoth': 'Укажите обе границы бюджета или оставьте их пустыми.', 'planner.errorBudgetRange': 'Проверьте минимальную и максимальную сумму бюджета.', 'planner.errorCheckData': 'Проверьте исходные данные.',
  'planner.dreamEyebrow': 'Начните с мечты', 'planner.dreamTitle': 'Какой должна быть поездка?', 'planner.describeAria': 'Опишите поездку', 'planner.routeEyebrow': '01 · Маршрут', 'planner.whenFrom': 'Когда и откуда', 'planner.origin': 'Город вылета', 'planner.originPlaceholder': 'Например, Алматы', 'planner.start': 'Начало', 'planner.return': 'Возвращение', 'planner.companyEyebrow': '02 · Компания', 'planner.who': 'Кто едет', 'planner.travelers': 'Путешественники', 'planner.decrease': 'Уменьшить количество', 'planner.increase': 'Увеличить количество', 'planner.travelerCount': 'Количество путешественников', 'planner.ages': 'Возраст, если это важно', 'planner.agesPlaceholder': 'Например, 34, 12', 'planner.commaSeparated': 'Через запятую', 'planner.meansEyebrow': '03 · Возможности', 'planner.tripBudget': 'Бюджет поездки', 'planner.budgetSkip': 'Можно пропустить — AI предложит реалистичный диапазон', 'planner.currency': 'Валюта', 'planner.minimum': 'Минимум', 'planner.maximum': 'Максимум', 'planner.noBudget': 'Не указывать бюджет', 'planner.savingChoice': 'Сохраняем выбор…', 'planner.continueAI': 'Продолжить с AI', 'planner.formFooter': 'AI задаст только важные уточнения и покажет сводку перед генерацией.',
  'memory.eyebrow': 'Память AI', 'memory.title': 'Использовать ваши сохранённые предпочтения из прошлых поездок?', 'memory.aria': 'Использовать сохранённые предпочтения', 'memory.yes': 'Да, учитывай их', 'memory.yesHint': 'AI мягко применит их к новому маршруту', 'memory.no': 'Нет, в этот раз без них', 'memory.noHint': 'План будет основан только на новом запросе', 'memory.note': 'Выбор сохранится как удобное значение по умолчанию, но его всегда можно поменять.',
  'dialog.intro': 'Уточню только то, что поможет сделать план точнее.', 'dialog.aria': 'Диалог с AI Planner', 'dialog.analyzing': 'Проверяю, достаточно ли деталей…', 'dialog.summarizing': 'Собираю сводку для подтверждения…', 'dialog.generating': 'Собираю полный маршрут…', 'dialog.answer': 'Ваш ответ', 'dialog.answerPlaceholder': 'Ответьте свободным текстом — можно сразу на все вопросы', 'dialog.continue': 'Продолжить диалог', 'dialog.retry': 'Попробовать ещё раз', 'dialog.reset': 'Изменить исходные данные',
  'confirm.unspecified': 'Не указано', 'confirm.datesUnspecified': 'Не указаны', 'confirm.age': 'возраст', 'confirm.budgetUnspecified': 'Не указан', 'confirm.eyebrow': 'Проверьте перед генерацией', 'confirm.title': 'Я правильно понял вашу поездку?', 'confirm.destination': 'Направление', 'confirm.departure': 'Отправление', 'confirm.dates': 'Даты и длительность', 'confirm.daysShort': 'дн.', 'confirm.travelers': 'Путешественники', 'confirm.budget': 'Бюджет', 'confirm.pace': 'Темп', 'confirm.interests': 'Интересы и пожелания', 'confirm.stayTransport': 'Жильё и транспорт', 'confirm.details': 'Важные детали', 'confirm.creating': 'Создаём маршрут…', 'confirm.wait': 'Подождите…', 'confirm.create': 'Да, создать полный маршрут', 'confirm.correction': 'Что нужно поправить?', 'confirm.correctionPlaceholder': 'Например: бюджет до 2 000 000 KZT, а темп хочу более расслабленный', 'confirm.updating': 'Обновляю сводку…', 'confirm.update': 'Обновить сводку',
  'generation.step1': 'Анализируем детали поездки…', 'generation.step2': 'Выстраиваем маршрут по дням…', 'generation.step3': 'Проверяем логистику и темп…', 'generation.step4': 'Считаем ориентировочный бюджет…', 'generation.step5': 'Подбираем жильё, еду и активности…', 'generation.step6': 'Собираем финальный план…', 'generation.eyebrow': 'AI создаёт ваше путешествие', 'generation.note': 'Большой персональный план требует немного времени. Можно оставаться на этой странице.',
  'generation.preparingLarge': 'Собираем основу большого путешествия…', 'generation.daysProgress': 'Готовим маршрут: дни {start}–{end}…', 'generation.finalizing': 'Объединяем части и проверяем весь план…', 'generation.largeNote': 'Объёмный маршрут создаётся отдельными проверяемыми блоками. Готовые части сохраняются в текущей генерации — не закрывайте страницу.',
  'planner.summaryError': 'Не удалось подготовить сводку. Попробуйте ещё раз.', 'planner.continueError': 'Не удалось продолжить планирование. Попробуйте ещё раз.', 'planner.preferenceError': 'Не удалось сохранить выбор предпочтений. Проверьте соединение и попробуйте ещё раз.', 'planner.generateError': 'Не удалось создать маршрут. Попробуйте ещё раз.', 'planner.loadingSettings': 'Загружаем настройки AI Planner…',
  'editor.example1': 'Добавь Венецию', 'editor.example2': 'Убери музеи', 'editor.example3': 'Добавь ещё 2 дня', 'editor.example4': 'Сделай маршрут менее насыщенным', 'editor.success': 'Маршрут обновлён с учётом вашей команды.', 'editor.error': 'Не удалось изменить маршрут. Попробуйте ещё раз.', 'editor.eyebrow': 'Настройте готовый план', 'editor.title': 'Измените маршрут короткой командой', 'editor.intro': 'AI сохранит остальной контекст и пересоберёт только то, чего касается изменение.', 'editor.examples': 'Примеры команд', 'editor.label': 'Что изменить?', 'editor.placeholder': 'Например: добавь свободный вечер в третий день', 'editor.updating': 'Обновляю план…', 'editor.apply': 'Применить изменение →', 'editor.status': 'Проверяю логистику, даты и нагрузку обновлённого маршрута…',
  'trip.noCost': 'Без затрат', 'trip.activePace': 'Насыщенный день', 'trip.balancedPace': 'Спокойный темп', 'trip.restPace': 'День отдыха', 'trip.day': 'День {day}', 'trip.aboutMinutes': 'Около {minutes} мин', 'trip.transferMinutes': 'Переезд {minutes} мин',
  'budget.typical': 'Расчёт по типичным ценам', 'budget.rough': 'Грубая оценка', 'budget.fallback': 'Стоимость зависит от сезона и доступности.', 'budget.eyebrow': 'Ориентировочный бюджет', 'budget.note': 'Сводная оценка, а не цена бронирования. Финальная стоимость зависит от сезона и доступности.', 'budget.typicalLegend': '● Типичные цены', 'budget.roughLegend': '○ Грубая оценка',
  'realism.okTitle': 'Маршрут проверен на реалистичность', 'realism.okText': 'Даты, нагрузка и время на переезды согласованы.', 'realism.adjusted': 'Маршрут скорректирован', 'realism.adjustedTitle': 'Так поездка останется выполнимой',
} as const;

const en: { [K in keyof typeof ru]: string } = {
  'planner.example1': 'A week in Japan with nature, intimate cafés, and an unhurried pace…', 'planner.example2': 'A February escape by the sea for two, with a beautiful hotel and fewer tourist crowds…', 'planner.example3': 'Plan a relaxed family journey through Italy with children…', 'planner.example4': 'I dream of seeing the northern lights and spending a few nights in a cosy cabin…',
  'planner.errorAges': 'Enter ages as whole numbers from 0 to 120, separated by commas.', 'planner.errorDatesBoth': 'Enter both trip dates or leave both fields empty.', 'planner.errorDatesOrder': 'The end date is earlier than the start date. Please correct the dates.', 'planner.errorAgeCount': 'There cannot be more ages than travellers.', 'planner.errorBudgetBoth': 'Enter both budget limits or leave both fields empty.', 'planner.errorBudgetRange': 'Check the minimum and maximum budget amounts.', 'planner.errorCheckData': 'Please review the trip details.',
  'planner.dreamEyebrow': 'Begin with the dream', 'planner.dreamTitle': 'What should this trip feel like?', 'planner.describeAria': 'Describe your trip', 'planner.routeEyebrow': '01 · Journey', 'planner.whenFrom': 'When and from where', 'planner.origin': 'Departure city', 'planner.originPlaceholder': 'For example, Almaty', 'planner.start': 'Start date', 'planner.return': 'Return date', 'planner.companyEyebrow': '02 · Travellers', 'planner.who': 'Who is going', 'planner.travelers': 'Travellers', 'planner.decrease': 'Decrease traveller count', 'planner.increase': 'Increase traveller count', 'planner.travelerCount': 'Number of travellers', 'planner.ages': 'Ages, if relevant', 'planner.agesPlaceholder': 'For example, 34, 12', 'planner.commaSeparated': 'Separated by commas', 'planner.meansEyebrow': '03 · Parameters', 'planner.tripBudget': 'Trip budget', 'planner.budgetSkip': 'Optional — AI can suggest a realistic range', 'planner.currency': 'Currency', 'planner.minimum': 'Minimum', 'planner.maximum': 'Maximum', 'planner.noBudget': 'Leave budget open', 'planner.savingChoice': 'Saving your choice…', 'planner.continueAI': 'Continue with AI', 'planner.formFooter': 'AI will ask only essential questions and show you a summary before generation.',
  'memory.eyebrow': 'AI memory', 'memory.title': 'Use your saved preferences from previous trips?', 'memory.aria': 'Use saved travel preferences', 'memory.yes': 'Yes, take them into account', 'memory.yesHint': 'AI will apply them gently to the new itinerary', 'memory.no': 'No, not for this trip', 'memory.noHint': 'The plan will use only your new request', 'memory.note': 'This becomes your convenient default, and you can change it whenever you wish.',
  'dialog.intro': 'I’ll clarify only what will make the plan more precise.', 'dialog.aria': 'Conversation with AI Planner', 'dialog.analyzing': 'Checking whether we have enough detail…', 'dialog.summarizing': 'Preparing a summary for your approval…', 'dialog.generating': 'Building the complete itinerary…', 'dialog.answer': 'Your answer', 'dialog.answerPlaceholder': 'Answer naturally — you can cover every question at once', 'dialog.continue': 'Continue the conversation', 'dialog.retry': 'Try again', 'dialog.reset': 'Change the starting details',
  'confirm.unspecified': 'Not specified', 'confirm.datesUnspecified': 'Not specified', 'confirm.age': 'ages', 'confirm.budgetUnspecified': 'Not specified', 'confirm.eyebrow': 'Review before generation', 'confirm.title': 'Have I understood your trip correctly?', 'confirm.destination': 'Destination', 'confirm.departure': 'Departure', 'confirm.dates': 'Dates and duration', 'confirm.daysShort': 'days', 'confirm.travelers': 'Travellers', 'confirm.budget': 'Budget', 'confirm.pace': 'Pace', 'confirm.interests': 'Interests and preferences', 'confirm.stayTransport': 'Stays and transport', 'confirm.details': 'Important details', 'confirm.creating': 'Creating your itinerary…', 'confirm.wait': 'One moment…', 'confirm.create': 'Yes, create the full itinerary', 'confirm.correction': 'What should be adjusted?', 'confirm.correctionPlaceholder': 'For example: budget up to KZT 2,000,000 and a more relaxed pace', 'confirm.updating': 'Updating the summary…', 'confirm.update': 'Update summary',
  'generation.step1': 'Reviewing the trip details…', 'generation.step2': 'Shaping the day-by-day itinerary…', 'generation.step3': 'Checking logistics and pace…', 'generation.step4': 'Estimating the budget…', 'generation.step5': 'Selecting stays, food, and experiences…', 'generation.step6': 'Assembling your final plan…', 'generation.eyebrow': 'AI is creating your journey', 'generation.note': 'A complete personal itinerary takes a little time. Please keep this page open.',
  'generation.preparingLarge': 'Building the foundation of your extended trip…', 'generation.daysProgress': 'Creating the itinerary for days {start}–{end}…', 'generation.finalizing': 'Joining the sections and checking the complete plan…', 'generation.largeNote': 'This detailed itinerary is created in smaller, verified sections. Completed sections remain available during this generation — please keep the page open.',
  'planner.summaryError': 'We couldn’t prepare the summary. Please try again.', 'planner.continueError': 'We couldn’t continue planning. Please try again.', 'planner.preferenceError': 'We couldn’t save your preference choice. Check your connection and try again.', 'planner.generateError': 'We couldn’t create the itinerary. Please try again.', 'planner.loadingSettings': 'Loading your AI Planner settings…',
  'editor.example1': 'Add Venice', 'editor.example2': 'Remove the museums', 'editor.example3': 'Add two more days', 'editor.example4': 'Make the itinerary less intense', 'editor.success': 'The itinerary has been updated with your instruction.', 'editor.error': 'We couldn’t update the itinerary. Please try again.', 'editor.eyebrow': 'Refine the finished plan', 'editor.title': 'Change the itinerary with one short instruction', 'editor.intro': 'AI keeps the rest of the context and rebuilds only what your change affects.', 'editor.examples': 'Example instructions', 'editor.label': 'What would you like to change?', 'editor.placeholder': 'For example: leave the third evening free', 'editor.updating': 'Updating the plan…', 'editor.apply': 'Apply change →', 'editor.status': 'Rechecking logistics, dates, and the pace of the updated itinerary…',
  'trip.noCost': 'No cost', 'trip.activePace': 'Full day', 'trip.balancedPace': 'Balanced pace', 'trip.restPace': 'Rest day', 'trip.day': 'Day {day}', 'trip.aboutMinutes': 'About {minutes} min', 'trip.transferMinutes': 'Transfer {minutes} min',
  'budget.typical': 'Based on typical prices', 'budget.rough': 'Rough estimate', 'budget.fallback': 'The final cost depends on season and availability.', 'budget.eyebrow': 'Indicative budget', 'budget.note': 'A planning estimate, not a booking quote. Final costs depend on season and availability.', 'budget.typicalLegend': '● Typical prices', 'budget.roughLegend': '○ Rough estimate',
  'realism.okTitle': 'Itinerary checked for realism', 'realism.okText': 'Dates, daily load, and transfer times are aligned.', 'realism.adjusted': 'Itinerary adjusted', 'realism.adjustedTitle': 'This keeps the journey achievable',
};

export const plannerTranslations = { ru, en };
