import type { DestinationText } from '../types';

export const englishDestinations: Record<string, DestinationText> = {
  istanbul: { city: 'Istanbul', country: 'Türkiye', badge: 'A city between two seas', description: 'The Bosphorus, palaces, vivid bazaars, and terrace dinners overlooking the old city.', visa: 'Visa-free', season: 'April — June', duration: '7 days · 2 travellers', price: 'from ₸620,000', rating: '4.9', reviews: '2,840 reviews', region: 'Eurasia', tags: ['City', 'Culture', 'Food'] },
  bali: { city: 'Bali', country: 'Indonesia', badge: 'An island of discovery', description: 'Tropical beaches, rice terraces, surf breaks, and serene villas wrapped in greenery.', visa: 'Visa on arrival', season: 'May — October', duration: '10 days · 2 travellers', price: 'from ₸1,180,000', rating: '4.9', reviews: '3,120 reviews', region: 'Southeast Asia', tags: ['Beach', 'Nature', 'Adventure'] },
  tokyo: { city: 'Tokyo', country: 'Japan', badge: 'Future meets tradition', description: 'Neon neighbourhoods, quiet gardens, exceptional food, and a city moving in perfect rhythm.', visa: 'Visa required', season: 'March — May', duration: '8 days · 2 travellers', price: 'from ₸1,420,000', rating: '4.9', reviews: '1,960 reviews', region: 'East Asia', tags: ['City', 'Culture', 'Food'] },
  singapore: { city: 'Singapore', country: 'Singapore', badge: 'A tropical metropolis', description: 'Futuristic architecture, lush gardens, immaculate streets, and flavours from across Asia.', visa: 'Visa required', season: 'February — April', duration: '6 days · 2 travellers', price: 'from ₸1,260,000', rating: '4.8', reviews: '1,540 reviews', region: 'Southeast Asia', tags: ['City', 'Nature', 'Food'] },
  tbilisi: { city: 'Tbilisi', country: 'Georgia', badge: 'A city with a warm soul', description: 'Old-town balconies, sulphur baths, wine bars, and mountain landscapes within easy reach.', visa: 'Visa-free', season: 'May — October', duration: '5 days · 2 travellers', price: 'from ₸410,000', rating: '4.9', reviews: '2,360 reviews', region: 'Caucasus', tags: ['City', 'Culture', 'Food', 'Nature'] },
  'hong-kong': { city: 'Hong Kong', country: 'China', badge: 'A city of contrasts', description: 'A cinematic harbour, soaring towers, green trails, and legendary street food.', visa: 'Visa-free up to 14 days', season: 'October — December', duration: '7 days · 2 travellers', price: 'from ₸1,090,000', rating: '4.8', reviews: '1,780 reviews', region: 'East Asia', tags: ['City', 'Nature', 'Adventure', 'Food'] },
  rome: { city: 'Rome', country: 'Italy', badge: 'The eternal classic', description: 'Ancient streets, remarkable art, intimate piazzas, and unhurried Italian evenings.', visa: 'Schengen visa', season: 'April — June', duration: '8 days · 2 travellers', price: 'from ₸1,350,000', rating: '4.9', reviews: '2,210 reviews', region: 'Europe', tags: ['City', 'Culture', 'Food'] },
  'nha-trang': { city: 'Nha Trang', country: 'Vietnam', badge: 'Sea meets city', description: 'A bright coastline, island escapes, fresh seafood, and a lively urban promenade.', visa: 'Visa-free up to 30 days', season: 'February — August', duration: '10 days · 2 travellers', price: 'from ₸940,000', rating: '4.8', reviews: '1,690 reviews', region: 'Southeast Asia', tags: ['Beach', 'City', 'Nature'] },
};
