export const catalogKk = {
  'catalog.eyebrow': 'Roamly топтамасы', 'catalog.title': 'Бағыттар', 'catalog.titleAccent': 'каталогы', 'catalog.intro': 'Шабадан жинауға тұрарлық орындар. Атмосферасын, бюджетін және кіру шарттарын салыстырып, қалғанын сапардың өзіне қалдырыңыз.',
  'catalog.resultOne': 'бағыт', 'catalog.resultFew': 'бағыт', 'catalog.resultMany': 'бағыт', 'catalog.sort': 'Сұрыптау', 'catalog.sortFeatured': 'Алдымен ұсынылғандар', 'catalog.sortCheap': 'Алдымен арзанырақ', 'catalog.sortExpensive': 'Алдымен қымбатырақ', 'catalog.sortRating': 'Рейтингі бойынша', 'catalog.sortAlphabetical': 'Әліпби бойынша',
  'catalog.emptyCount': '0 бағыт', 'catalog.emptyTitle': 'Көкжиекті кеңейтеміз бе?', 'catalog.emptyText': 'Бұл сүзгілерге сәйкес ештеңе табылмады. Кейбір шарттарды алып тастаңыз немесе қайта бастаңыз.', 'catalog.reset': 'Сүзгілерді тазарту',
  'filters.label': 'Бағыт сүзгілері', 'filters.title': 'Өзіңізге сай бағытты табыңыз', 'filters.resetAll': 'Барлығын тазарту', 'filters.region': 'Аймақ', 'filters.allRegions': 'Барлық аймақ', 'filters.rating': 'Ең төмен рейтинг', 'filters.any': 'Кез келген', 'filters.visa': 'Виза тәртібі', 'filters.budget': 'Сапар бюджеті', 'filters.from': '{price} бастап', 'filters.to': '{price} дейін', 'filters.minPrice': 'Ең төмен баға', 'filters.maxPrice': 'Ең жоғары баға', 'filters.interests': 'Сізге не қызық', 'filters.anyTag': 'таңдалған тегтердің кез келгені',
  'filters.regionEurasia': 'Еуразия', 'filters.regionCaucasus': 'Кавказ', 'filters.regionEurope': 'Еуропа', 'filters.regionEastAsia': 'Шығыс Азия', 'filters.regionSoutheastAsia': 'Оңтүстік-Шығыс Азия', 'filters.beach': 'Жағажай', 'filters.culture': 'Мәдениет', 'filters.adventure': 'Шытырман оқиға', 'filters.city': 'Қала', 'filters.nature': 'Табиғат', 'filters.food': 'Гастрономия', 'filters.visaFree': 'Визасыз', 'filters.visaArrival': 'Келгенде', 'filters.visaAdvance': 'Алдын ала',
  'vote.loadError': 'Даусыңызды жүктей алмадық.', 'vote.saveError': 'Дауысты сақтай алмадық. Интернетті тексеріп, қайталап көріңіз.', 'vote.eyebrow': 'Қауымдастық таңдауы', 'vote.shareDream': 'Армандаған бағытыңызбен бөлісіңіз', 'vote.leaderFallback': 'Қазір бұл Roamly саяхатшылары ең көп қалайтын бағыт.', 'vote.prompt': 'Ұсыныстардан нақты қаланы таңдаңыз. Бір аккаунтта бір өзекті дауыс сақталады.', 'vote.total': 'барлық дауыс', 'vote.top': 'Үздік 4 бағыт', 'vote.statsUnavailable': 'Статистика уақытша қолжетімсіз', 'vote.checking': 'Аккаунт тексерілуде…', 'vote.signInPrompt': 'Дауыс беру үшін аккаунтқа кіріңіз.', 'vote.login': 'Кіру', 'vote.signup': 'Тіркелу', 'vote.current': 'Қазіргі таңдауыңыз:', 'vote.question': 'Қайда барғыңыз келеді?', 'vote.saved': 'Дауыс сақталды!', 'vote.saving': 'Сақталуда…', 'vote.change': 'Дауысты өзгерту', 'vote.submit': 'Дауыс беру',
  'map.eyebrow': 'Әлемді зерттеңіз', 'map.title': 'Барлық бағыт.', 'map.titleAccent': 'Бір картада.', 'map.countText': 'Еуропадан Азияға дейінгі орын. Толығырақ танысу үшін белгіні басыңыз.', 'map.hint': 'Картаны жылжытып, масштабтаңыз', 'map.close': 'Алдын ала көріністі жабу', 'map.tripEstimate': 'Сапардың шамамен бюджеті', 'map.openGuide': 'Гидті ашу', 'map.aria': 'Бағыттардың интерактивті картасы',
  'guide.notFound': 'Бағыт табылмады', 'guide.backCatalog': 'Каталогқа оралу', 'guide.nextStep': 'Келесі қадам', 'guide.planTitle': 'Сапарды өзіңізге бейімдеңіз', 'guide.createRoute': 'Маршрут құру', 'guide.panorama': '{city} панорамасы', 'guide.all': 'Барлық бағыт', 'guide.label': 'Саяхат гиді', 'guide.updated': '2026 жылғы 12 тамызда жаңартылды', 'guide.scroll': 'Гидке өту', 'guide.inThisGuide': 'Бұл гидте', 'guide.whatToSee': 'Не көруге болады', 'guide.seasonBudget': 'Маусым және бюджет', 'guide.goodToKnow': 'Білген жөн', 'guide.whyGo': 'Неліктен баруға тұрарлық', 'guide.highlights': 'Ең маңыздысы', 'guide.highlightsText': 'Белгі қоюға арналған тізім емес, бағыттың мінезін жақсы ашатын орындар.', 'guide.beforeTrip': 'Сапар алдында', 'guide.practical': 'Практикалық мәліметтер', 'guide.when': 'Қашан барған дұрыс', 'guide.climate': 'Климат және маусым', 'guide.entry': 'Виза және кіру · Қазақстан паспорты', 'guide.estimate': 'Шамамен есеп', 'guide.howMuch': 'Қанша қаражат жоспарлау керек', 'guide.budgetNote': 'Ұшуды қоспағандағы орташа жайлы бюджет. Бағалар маусым мен валюта бағамына байланысты өзгереді.', 'guide.knowAhead': 'Алдын ала біліңіз', 'guide.calmTitle': 'Сенімді саяхаттаңыз', 'guide.calmText': 'Алаңдауға себеп емес — жағымсыз тосынсыйларды болдырмауға көмектесетін бірнеше жайт қана.', 'guide.culture': 'Мәдени ерекшеліктер', 'guide.prepareFor': 'Неге дайын болу керек',
} as const;
