export const commonKk = {
  'city.placeholder': 'Қаланы жаза бастаңыз', 'city.searchError': 'Қалаларды таба алмадық. Қайталап көріңіз.', 'city.choose': 'Ұсыныстар тізімінен қаланы таңдаңыз.', 'city.searching': 'Қалаларды іздеп жатырмыз', 'city.empty': 'Қалалар табылмады',
  'guest.browserError': 'Маршрутты уақытша сақтау мүмкін болмады. Браузерде орын босатып, қайталап көріңіз.', 'guest.close': 'Жабу', 'guest.eyebrow': 'Алғашқы маршрутыңыз дайын', 'guest.title': 'Бұл сапарды сақтап, жаңа саяхаттарды жоспарлаңыз', 'guest.text': 'Жаңа маршруттар құрып, жоспарларыңызға кез келген уақытта оралу үшін тегін тіркеліңіз.', 'guest.signup': 'Тегін тіркелу', 'guest.login': 'Аккаунтым бар',
  'setup.title': 'Алдымен Supabase-ті қосыңыз', 'setup.text': '.env.example файлын .env ретінде көшіріп, жобаңыздың URL мекенжайы мен Publishable key кілтін енгізіңіз.',
  'quick.destination': 'Қайда барғыңыз келеді?', 'quick.daysNights': 'Күн / түн', 'quick.days': 'Күн саны', 'quick.nights': 'Түн саны', 'quick.travelers': 'Саяхатшылар', 'quick.people': '{count} адам', 'quick.style': 'Сапар стилі', 'quick.comfort': 'Жайлы', 'quick.economy': 'Үнемді', 'quick.premium': 'Премиум', 'quick.submit': 'Жоспар құру →',
  'extras.road': 'Жол және қала', 'extras.transport': 'Көлік', 'extras.stayEyebrow': 'Қайда тоқтауға болады', 'extras.stays': 'Тұратын орындар', 'extras.foodEyebrow': 'Бағыттың дәмі', 'extras.food': 'Мейрамханалар мен тағамдар', 'extras.overview': 'Жалпы шолу', 'extras.activities': 'Іс-шаралар', 'extras.before': 'Сапар алдында', 'extras.links': 'Пайдалы сілтемелер', 'extras.remember': 'Ештеңені ұмытпау', 'extras.checklist': 'Дайындық тізімі', 'extras.perNight': '/ түн',
  'extras.tierFilter': 'Деңгей бойынша сүзгі', 'extras.tier.all': 'Барлығы', 'extras.tier.budget': 'Үнемді', 'extras.tier.comfortable': 'Жайлы', 'extras.tier.luxury': 'Сәнді',
  'extras.photoLoading': 'Фотосурет жүктелуде', 'extras.photoExact': 'Орынның фотосуреті', 'extras.photoExactAlt': '«{name}» орнының фотосуреті',
  'routeMap.dayMeta': '{day}-күн · {time}', 'routeMap.area': 'аудан бойынша шамамен', 'routeMap.alt': '{title}, {day}-күн', 'routeMap.aria': 'Маршрут нүктелерінің интерактивті картасы',
  'password.levelWeak': 'Әлсіз', 'password.levelMedium': 'Орташа', 'password.levelStrong': 'Сенімді', 'password.hintLength': 'кемінде 10 таңба', 'password.hintGroups': 'бас және кіші әріптер, сандар немесе таңбалар', 'password.hintPatterns': 'қарапайым тізбектер мен қайталауларсыз',
} as const;
